### ISSUE TITLE
Cannot get it to run, keep getting 'Icon' does not exist and more messages

### ISSUE THREAD

**Issue by AmberElferink** [TheCreatorJames/DotNetCompressor#2]
![image](https://user-images.githubusercontent.com/32518317/40662462-b4804820-6356-11e8-987d-f5566b594d9f.png)

This is how my visual studio currently looks like. As you can see I installed the libraries and referenced them. Then again, I am still a noob coming to installing libraries in VS. Is there anything I'm doing wrong?

**Comment by TotalTechGeek** [comment]
Oh, yikes. I think I might've left out a few steps in the build setup. 

You'd have to add a reference to "System.Drawing" I believe (right click on References). 

It's been a few years since I've worked on this project, but I'll try publishing an update (in the next few hours) with the project file already configured.

Fortunately, I just located the original project, so it won't take too long.

**Comment by TotalTechGeek** [comment]
About to push the new update, which also involved a change of library. I'm now using "SharpCompress" instead of SevenZipSharp. You should also have a much easier time building the project :)

This update also resolves any licensing ambiguity. 

----

Please keep in mind that the code in this project is not particularly good - it was written in a time span of about 8 hours.

---- 

There is a minor issue introduced by the new update, SharpCompress produces a slightly larger dll, which makes its improvements over GZip far less dramatic. 

I will resolve this at a later date by forking the project and producing minimal builds for it.
